ARG BASE_IMG_TAG
ARG BASE_IMG_NAME
FROM ${BASE_IMG_NAME}:${BASE_IMG_TAG}


# will run on http://127.0.0.1:11434

# docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama

# docker run --name ollama-test -itd -v ollama:/root/.ollama -p 11434:11434 ollama/ollama




